import streamlit as st
import datetime
import numpy as np
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

# ---------------------------
# APP HEADER
# ---------------------------
st.set_page_config(page_title="Beam Moment Capacity - NZS 3101", layout="centered")

st.title("VISKAR ENGINEERS")
st.subheader("Single Reinforced Rectangular Beam Capacity Calculator (NZS 3101)")

st.write("### Input Parameters")

# ---------------------------
# INPUT FIELDS
# ---------------------------
b = st.number_input("Width b (mm)", value=300.0)
D = st.number_input("Overall Depth D (mm)", value=450.0)
cover = st.number_input("Clear Cover (mm)", value=40.0)
fc = st.number_input("Concrete Strength f'c (MPa)", value=25.0)
fy = st.number_input("Steel Strength fy (MPa)", value=500.0)
E_conc = st.number_input("E_concrete (GPa)", value=23.0)
E_steel = st.number_input("E_steel (GPa)", value=200.0)
Ast = st.number_input("Tensile Reinforcement (mm²)", value=3 * np.pi * (16**2) / 4)
Asc = st.number_input("Compression Reinforcement (mm²)", value=3 * np.pi * (10**2) / 4)

# ---------------------------
# CALCULATION BUTTON
# ---------------------------
if st.button("Calculate Beam Capacity"):
    d = D - cover - 16/2  # effective depth (approx)
    a_guess = 100.0
    beta1 = 0.85  # NZS 3101: β1 for fc' ≤ 28 MPa
    fcd = 0.85 * fc / 1.0  # Design strength approx (NZS 3101: Cl. 9.2.3.2)
    fs = 0.85 * fy  # Assume steel at 0.85fy for balanced condition

    # Simplified moment capacity
    a = (Ast * fy) / (0.85 * fc * b)
    c = a / beta1
    jd = d - a / 2
    Mu = (Ast * fy * jd) / 1e6  # in kN·m

    st.success(f"**Ultimate Moment Capacity (φMu)** ≈ {Mu:.2f} kN·m")

    # ---------------------------
    # REPORT GENERATION
    # ---------------------------
    st.write("### Detailed Report")

    # Add date
    date_str = datetime.datetime.now().strftime("%d-%b-%Y %H:%M")

    st.markdown(f"""
    **Report Title:** Beam Moment Capacity Check per NZS 3101  
    **Generated by:** VISKAR ENGINEERS  
    **Date:** {date_str}

    **Given Data**
    - b = {b} mm  
    - D = {D} mm  
    - Clear cover = {cover} mm  
    - f'c = {fc} MPa  
    - fy = {fy} MPa  
    - E_concrete = {E_conc} GPa  
    - E_steel = {E_steel} GPa  
    - Ast = {Ast:.1f} mm²  
    - Asc = {Asc:.1f} mm²  

    **Calculated Parameters**
    - β₁ = {beta1} (NZS 3101: Cl 9.2.7.3)
    - a = {a:.2f} mm (Equivalent compression block depth)
    - jd = {jd:.2f} mm (Lever arm)
    - φMu = {Mu:.2f} kN·m (Nominal ultimate moment)

    **References**
    - NZS 3101: Part 1 – Concrete Structures Standard  
      • Cl 9.2.3 – Concrete Strength Reduction  
      • Cl 9.2.7.3 – Equivalent Rectangular Stress Block  
      • Cl 9.3.1 – Flexural Strength of Members  
    """)

    # ---------------------------
    # PDF CREATION
    # ---------------------------
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 14)
    c.drawCentredString(width/2, height - 40, "VISKAR ENGINEERS")
    c.setFont("Helvetica", 11)
    c.drawString(40, height - 70, f"Beam Moment Capacity Report per NZS 3101")
    c.drawString(40, height - 85, f"Date: {date_str}")

    y = height - 120
    lines = [
        f"b = {b} mm, D = {D} mm, Cover = {cover} mm",
        f"f'c = {fc} MPa, fy = {fy} MPa",
        f"E_concrete = {E_conc} GPa, E_steel = {E_steel} GPa",
        f"Ast = {Ast:.1f} mm², Asc = {Asc:.1f} mm²",
        f"a = {a:.2f} mm, jd = {jd:.2f} mm",
        f"Ultimate Moment Capacity (φMu) = {Mu:.2f} kN·m",
        "",
        "NZS 3101 References:",
        "  - Cl. 9.2.3 : Concrete Strength Reduction",
        "  - Cl. 9.2.7.3 : Equivalent Rectangular Stress Block",
        "  - Cl. 9.3.1 : Flexural Strength of Members",
    ]
    for line in lines:
        c.drawString(40, y, line)
        y -= 18

    c.showPage()
    c.save()
    buffer.seek(0)

    # ---------------------------
    # DOWNLOAD BUTTON
    # ---------------------------
    st.download_button(
        label="📄 Print / Download Report (PDF)",
        data=buffer,
        file_name=f"Beam_Moment_Report_{date_str.replace(':','-').replace(' ','_')}.pdf",
        mime="application/pdf",
    )
